# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="rbates"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rvm jobber bundler)

source $ZSH/oh-my-zsh.sh

# use vim as an editor
export EDITOR=vim

# vi mode
bindkey -v
bindkey "^F" vi-cmd-mode
bindkey jj vi-cmd-mode

# use incremental search
bindkey "^R" history-incremental-search-backward

# add some readline keys back
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

# handy keybindings
bindkey "^P" history-search-backward
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word


# Customize to your needs...
alias rake='noglob rake'
#alias heroku='noglob heroku'
alias tmux="TERM=screen-256color-bce tmux"

# these are repeated in the jobber plugin, but aren't loading for soem reason
alias jc='cd ~/jobber/code'
alias jcs='cd ~/jobber/code && rails s webrick'
alias jcse='cd ~/jobber/code && rake sunspot:solr:run'
alias jcm='cd ~/jobber/code && mvim .'

# MacPorts Installer addition on 2010-05-30_at_14:48:00: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

if [[ -s $HOME/.profile ]] ; then source $HOME/.profile ; fi


### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
